/*
 * Arun K
 *Septembre 28 2019
 */

/**
 *
 * @author arkir7294
 */
public class MultipleChoiceQuestion extends javax.swing.JFrame {
    
//Variable Declaration Area 
    int incorrect = 0;
     int correct = 0;
     double percentage = 10;
     double totalpercentage;
    
    /**
     * Creates new form MultipleChoiceQuestion
     */
    public MultipleChoiceQuestion() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Quiz = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        MnS2_lbl = new javax.swing.JLabel();
        CH3COOH_txt = new javax.swing.JTextField();
        lbl_CH3COOH = new javax.swing.JLabel();
        MagnesiumPhosphate_lbl = new javax.swing.JLabel();
        SodiumSulfate_lbl = new javax.swing.JLabel();
        Li3PO4_lbl = new javax.swing.JLabel();
        Hypochlorite_lbl = new javax.swing.JLabel();
        PerbromicAcid_lbl = new javax.swing.JLabel();
        Percarbonate_lbl = new javax.swing.JLabel();
        NO_lbl = new javax.swing.JLabel();
        NiI3_lbl = new javax.swing.JLabel();
        NiI3_txt = new javax.swing.JTextField();
        Hypochlorite_txt = new javax.swing.JTextField();
        NO_txt = new javax.swing.JTextField();
        MagnesiumPhosphate_txt = new javax.swing.JTextField();
        MnS2_txt = new javax.swing.JTextField();
        Li3PO4_txt = new javax.swing.JTextField();
        Percarbonate_txt = new javax.swing.JTextField();
        PerbromicAcid_txt = new javax.swing.JTextField();
        SodiumSulfate_txt = new javax.swing.JTextField();
        SubmitButton = new javax.swing.JButton();
        Correction1_txt = new javax.swing.JTextField();
        Correction2_txt = new javax.swing.JTextField();
        Correction3_txt = new javax.swing.JTextField();
        Correction4_txt = new javax.swing.JTextField();
        Correction5_txt = new javax.swing.JTextField();
        Correction6_txt = new javax.swing.JTextField();
        Correction7_txt = new javax.swing.JTextField();
        Correction8_txt = new javax.swing.JTextField();
        Correction10_txt = new javax.swing.JTextField();
        Correction9_txt = new javax.swing.JTextField();
        Correct_lbl = new javax.swing.JLabel();
        Percentage_lbl = new javax.swing.JLabel();
        Incorrect_lbl = new javax.swing.JLabel();
        Incorrect_txt = new javax.swing.JTextField();
        Correct_txt = new javax.swing.JTextField();
        Percentage_txt = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTitle.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        lblTitle.setText("Nomenclature Quiz");

        MnS2_lbl.setText("What is the chemical name of MnS2?");

        CH3COOH_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CH3COOH_txtActionPerformed(evt);
            }
        });

        lbl_CH3COOH.setText("What is the chemical name of CH3COOH?");

        MagnesiumPhosphate_lbl.setText("What is the chemical formula for magnesium phosphate heptahydrate?");

        SodiumSulfate_lbl.setText("What is the chemical name for Na2SO4 • 10H20?");

        Li3PO4_lbl.setText("What is the formula for lithium phosphate?");

        Hypochlorite_lbl.setText("What is the chemical formula of hypochlorite? ");

        PerbromicAcid_lbl.setText("What is the formula for perbromic acid?");

        Percarbonate_lbl.setText("What is the chemical formula of percarbonate?");

        NO_lbl.setText("What are the characteristics of the bond between nitrogen and oxygen?");

        NiI3_lbl.setText("What is the formula for nickel(III) iodide?");

        NiI3_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NiI3_txtActionPerformed(evt);
            }
        });

        Hypochlorite_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Hypochlorite_txtActionPerformed(evt);
            }
        });

        NO_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NO_txtActionPerformed(evt);
            }
        });

        MagnesiumPhosphate_txt.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
                MagnesiumPhosphate_txtAncestorRemoved(evt);
            }
        });
        MagnesiumPhosphate_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MagnesiumPhosphate_txtActionPerformed(evt);
            }
        });

        MnS2_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnS2_txtActionPerformed(evt);
            }
        });

        Li3PO4_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Li3PO4_txtActionPerformed(evt);
            }
        });

        Percarbonate_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Percarbonate_txtActionPerformed(evt);
            }
        });

        PerbromicAcid_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PerbromicAcid_txtActionPerformed(evt);
            }
        });

        SodiumSulfate_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SodiumSulfate_txtActionPerformed(evt);
            }
        });

        SubmitButton.setText("Submit");
        SubmitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitButtonActionPerformed(evt);
            }
        });

        Correction1_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Correction1_txtActionPerformed(evt);
            }
        });

        Correction2_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Correction2_txtActionPerformed(evt);
            }
        });

        Correct_lbl.setText("Total Correct:");

        Percentage_lbl.setText("Percentage:");

        Incorrect_lbl.setText("Total Incorrect:");

        javax.swing.GroupLayout QuizLayout = new javax.swing.GroupLayout(Quiz);
        Quiz.setLayout(QuizLayout);
        QuizLayout.setHorizontalGroup(
            QuizLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(QuizLayout.createSequentialGroup()
                .addGap(413, 413, 413)
                .addComponent(SubmitButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(QuizLayout.createSequentialGroup()
                .addGroup(QuizLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(QuizLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(QuizLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(NiI3_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(QuizLayout.createSequentialGroup()
                                .addComponent(NiI3_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(Correction2_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(QuizLayout.createSequentialGroup()
                                .addComponent(Hypochlorite_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Correction3_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(NO_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 514, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Hypochlorite_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(MagnesiumPhosphate_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 514, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_CH3COOH)
                            .addGroup(QuizLayout.createSequentialGroup()
                                .addComponent(CH3COOH_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(Correction1_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(QuizLayout.createSequentialGroup()
                                .addComponent(NO_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Correction4_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(QuizLayout.createSequentialGroup()
                                .addGroup(QuizLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(Correct_lbl)
                                    .addComponent(MagnesiumPhosphate_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Incorrect_lbl)
                                    .addComponent(Percentage_lbl))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Correction5_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(QuizLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(QuizLayout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addGroup(QuizLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Percarbonate_lbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(QuizLayout.createSequentialGroup()
                                        .addGroup(QuizLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(QuizLayout.createSequentialGroup()
                                                .addComponent(PerbromicAcid_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(Correction9_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(MnS2_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(Li3PO4_lbl)
                                            .addGroup(QuizLayout.createSequentialGroup()
                                                .addComponent(MnS2_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(Correction6_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(PerbromicAcid_lbl)
                                            .addGroup(QuizLayout.createSequentialGroup()
                                                .addComponent(Li3PO4_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(Correction7_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(QuizLayout.createSequentialGroup()
                                                .addComponent(Percarbonate_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(Correction8_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addGroup(QuizLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(QuizLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(SodiumSulfate_lbl, javax.swing.GroupLayout.DEFAULT_SIZE, 369, Short.MAX_VALUE)
                                    .addGroup(QuizLayout.createSequentialGroup()
                                        .addComponent(SodiumSulfate_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(27, 27, 27)
                                        .addComponent(Correction10_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))))))
                    .addGroup(QuizLayout.createSequentialGroup()
                        .addGroup(QuizLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(QuizLayout.createSequentialGroup()
                                .addGap(304, 304, 304)
                                .addGroup(QuizLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(Correct_txt, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Incorrect_txt, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Percentage_txt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(QuizLayout.createSequentialGroup()
                                .addGap(322, 322, 322)
                                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        QuizLayout.setVerticalGroup(
            QuizLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(QuizLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(QuizLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_CH3COOH, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MnS2_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(QuizLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CH3COOH_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MnS2_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Correction1_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Correction6_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(QuizLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NiI3_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Li3PO4_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(QuizLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NiI3_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Correction2_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Li3PO4_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Correction7_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(QuizLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(QuizLayout.createSequentialGroup()
                        .addGap(271, 271, 271)
                        .addGroup(QuizLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(MagnesiumPhosphate_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SodiumSulfate_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(QuizLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(QuizLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Hypochlorite_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Percarbonate_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(QuizLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Hypochlorite_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Correction3_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Percarbonate_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Correction8_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34)
                        .addGroup(QuizLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(NO_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PerbromicAcid_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(7, 7, 7)
                        .addGroup(QuizLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(NO_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Correction4_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PerbromicAcid_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Correction9_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(52, 52, 52)
                .addGroup(QuizLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MagnesiumPhosphate_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Correction5_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SodiumSulfate_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Correction10_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(SubmitButton)
                .addGap(24, 24, 24)
                .addGroup(QuizLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Correct_lbl)
                    .addComponent(Correct_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(QuizLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Incorrect_lbl)
                    .addComponent(Incorrect_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(QuizLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Percentage_lbl)
                    .addComponent(Percentage_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Quiz, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Quiz, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NO_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NO_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NO_txtActionPerformed

    private void MagnesiumPhosphate_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MagnesiumPhosphate_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MagnesiumPhosphate_txtActionPerformed

    private void MnS2_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnS2_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MnS2_txtActionPerformed

    private void Li3PO4_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Li3PO4_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Li3PO4_txtActionPerformed

    private void Percarbonate_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Percarbonate_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Percarbonate_txtActionPerformed

    private void PerbromicAcid_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PerbromicAcid_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PerbromicAcid_txtActionPerformed

    private void SodiumSulfate_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SodiumSulfate_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SodiumSulfate_txtActionPerformed

    private void CH3COOH_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CH3COOH_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CH3COOH_txtActionPerformed

    private void SubmitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitButtonActionPerformed
        
        //Correction Marks
        String CHECKMARK = "✓";
        String INCORRECTMARK = "X";
        
        //Acetic Acid Questionx`
        final String QUESTION1;
        final String ANSWER1 = "Acetic Acid";
        final String ANSWER2 = "acetic acid";
        final String ANSWER3 = "Aqueous Hydrogen Acetate";
        final String ANSWER4 = "aqueous hydrogen acetate";
        String answer5 = "Aqueous hydrogen acetate";
        
         //Acetic Acid
        QUESTION1 = CH3COOH_txt.getText();
        
          if (QUESTION1.equals(ANSWER1)){
            Correction1_txt.setText(CHECKMARK);
            correct = correct + 1;
          }else if(QUESTION1.equals(ANSWER2)){
            Correction1_txt.setText(CHECKMARK);
            correct = correct + 1;
          }else if(QUESTION1.equals(ANSWER3)){
            Correction1_txt.setText(CHECKMARK);
            correct = correct + 1;
          }else if(QUESTION1.equals(ANSWER4)){
            Correction1_txt.setText(CHECKMARK);
            correct = correct + 1;
          }else if(QUESTION1.equals(answer5)){
            Correction1_txt.setText(CHECKMARK);
            correct = correct + 1;
          } else {
            Correction1_txt.setText(INCORRECTMARK);
            incorrect = incorrect + 1;
          }
       
        //Nickle (III) Iodide Question
        final String QUESTION2;
        final String ANSWER6 = "NiI3";
       
          //Nickel (III) Iodide
          QUESTION2 = NiI3_txt.getText();
        
          if (QUESTION2.equals(ANSWER6)){
            Correction2_txt.setText(CHECKMARK);
            correct = correct + 1;
          }else{
            Correction2_txt.setText(INCORRECTMARK);
            incorrect = incorrect + 1;
          }
        
        //Hypochlorite Question
        String QUESTION3;
        String ANSWER7 = "ClO";        
        
          //Hypochlorite
         QUESTION3 = Hypochlorite_txt.getText();
        
          if (QUESTION3.equals (ANSWER7)){
            Correction3_txt.setText(CHECKMARK);
            correct = correct + 1;
          }else{
            Correction3_txt.setText(INCORRECTMARK);
            incorrect = incorrect + 1;
          } 
        
        //Nitrogen Oxide Question
        final String QUESTION4;
        final String ANSWER8 = "Polar Covalent";
        final String ANSWER9 = "polar covalent";
        String ANSWER10 = "Polar covalent";
        
          //Nitrogen Oxide
          QUESTION4 = NO_txt.getText();
        
          if (QUESTION4.equals (ANSWER8)){
           Correction4_txt.setText(CHECKMARK);
           correct = correct + 1;
          }else if(QUESTION4.equals (ANSWER9)){
           Correction4_txt.setText(CHECKMARK);
           correct = correct + 1;
          }else if (QUESTION4.equals (ANSWER10)){
           Correction4_txt.setText(CHECKMARK);
           correct = correct + 1;
          }else{
           Correction4_txt.setText(INCORRECTMARK);
           incorrect = incorrect + 1;
          }
       
        //Magnesium Phosphate Heptahydrate Question 
        final String QUESTION5; 
        final String ANSWER11 = "Mg3(PO4)2 • 7H2O";
        final String ANSWER12 = "Mg3(PO4)2•7H2O";
        String ANSWER13 = "Mg3 (PO4)2 •7H2O";
                                
          //Magnesium Phosphate Heptahydrate
          QUESTION5 = MagnesiumPhosphate_txt.getText();
        
          if (QUESTION5.equals (ANSWER11)){
              Correction5_txt.setText(CHECKMARK);
              correct = correct + 1;
          }else if(QUESTION5.equals (ANSWER12)){
              Correction5_txt.setText(CHECKMARK);
              correct = correct + 1;
          }else if (QUESTION5.equals (ANSWER13)){
              Correction5_txt.setText(CHECKMARK);
              correct = correct + 1;
          }else{
              Correction5_txt.setText(INCORRECTMARK);
              incorrect = incorrect + 1;
          }
          
        //MnS2 Question
        final String QUESTION6;
        final String ANSWER14 = "Manganese (IV) Sulfide";
        final String ANSWER15 = "manganese (IV) sulfide";
        final String ANSWER16 = "manganese(IV) sulfide";
        final String ANSWER17 = "Manganese(IV) sulfide";
        String ANSWER18 = "Manganese(IV) Sulfide";
        
          //MnS2
          QUESTION6 = MnS2_txt.getText();
         
          if (QUESTION6.equals (ANSWER14)){
             Correction6_txt.setText(CHECKMARK);
             correct = correct + 1;
          }else if(QUESTION6.equals (ANSWER15)){
             Correction6_txt.setText(CHECKMARK);
             correct = correct + 1;
          }else if(QUESTION6.equals (ANSWER16)){
             Correction6_txt.setText(CHECKMARK);
             correct = correct + 1;
          }else if(QUESTION6.equals (ANSWER17)){
             Correction6_txt.setText(CHECKMARK);
             correct = correct + 1;
          }else if(QUESTION6.equals (ANSWER18)){
             Correction6_txt.setText(CHECKMARK);
             correct = correct + 1;
          }else{
             Correction6_txt.setText(INCORRECTMARK);
             incorrect = incorrect + 1;
          }
        
        //Lithium Phosphate Question
        String QUESTION7;
        String ANSWER19 = "Li3PO4";
         
          //Lithium Phosphate
          QUESTION7 = Li3PO4_txt.getText();
        
          if (QUESTION7.equals (ANSWER19)){
             Correction7_txt.setText(CHECKMARK);
             correct = correct + 1;
          }else{
             Correction7_txt.setText(INCORRECTMARK);
             incorrect = incorrect + 1;
          }
         
        //Percarbonate Question 
        final String QUESTION8;
        final String ANSWER20 = "CO4";
         
          //Percarbonate 
          QUESTION8 = Percarbonate_txt.getText();
         
          if (QUESTION8.equals (ANSWER20)){
             Correction8_txt.setText(CHECKMARK);
             correct = correct + 1;
          }else{
             Correction8_txt.setText(INCORRECTMARK);
             incorrect = incorrect + 1;
          }
         
        //Perbromic Acid Question
        String QUESTION9;
        String ANSWER21 = "HBrO4";
         
          //Perbromic Acid
          QUESTION9 = PerbromicAcid_txt.getText();
         
          if (QUESTION9.equals (ANSWER21)){
             Correction9_txt.setText(CHECKMARK);
             correct = correct + 1;
          }else{
             Correction9_txt.setText(INCORRECTMARK);
             incorrect = incorrect + 1;
          }
          
        //Sodium Sulfate Decahydrate Question
        String QUESTION10;
        final String ANSWER22 = "Sodium Sulfate Decahydrate";
        final String ANSWER23 = "Sodium sulfate decahydrate";
        String ANSWER24 = "sodium sulfate decahydrate";
        
          //Sodium Sulfate Decahydrate
          QUESTION10 = MagnesiumPhosphate_txt.getText();
        
          if (QUESTION10.equals (ANSWER22)){
            Correction10_txt.setText(CHECKMARK);
            correct = correct + 1;
          }else if(QUESTION10.equals (ANSWER23)){
            Correction10_txt.setText(CHECKMARK);
            correct = correct + 1;
          }else if(QUESTION10.equals (ANSWER24)){
            Correction10_txt.setText(CHECKMARK);
            correct = correct + 1;
          }else{
            Correction10_txt.setText(INCORRECTMARK);
            incorrect = incorrect + 1;
          } 
        
        //Total Correct
        Correct_txt.setText(String.valueOf(correct));
        
        //Total Incorrect
        Incorrect_txt.setText(String.valueOf(incorrect));
         
        //Percentage
        totalpercentage = correct / percentage;
        totalpercentage = totalpercentage * 100;
        Percentage_txt.setText(String.valueOf(totalpercentage));
         
         
         
         
         
         
         
         
         
    }//GEN-LAST:event_SubmitButtonActionPerformed

    private void Correction1_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Correction1_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Correction1_txtActionPerformed

    private void NiI3_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NiI3_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NiI3_txtActionPerformed

    private void Correction2_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Correction2_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Correction2_txtActionPerformed

    private void Hypochlorite_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Hypochlorite_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Hypochlorite_txtActionPerformed

    private void MagnesiumPhosphate_txtAncestorRemoved(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_MagnesiumPhosphate_txtAncestorRemoved
        // TODO add your handling code here:
    }//GEN-LAST:event_MagnesiumPhosphate_txtAncestorRemoved

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MultipleChoiceQuestion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MultipleChoiceQuestion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MultipleChoiceQuestion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MultipleChoiceQuestion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MultipleChoiceQuestion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CH3COOH_txt;
    private javax.swing.JLabel Correct_lbl;
    private javax.swing.JTextField Correct_txt;
    private javax.swing.JTextField Correction10_txt;
    private javax.swing.JTextField Correction1_txt;
    private javax.swing.JTextField Correction2_txt;
    private javax.swing.JTextField Correction3_txt;
    private javax.swing.JTextField Correction4_txt;
    private javax.swing.JTextField Correction5_txt;
    private javax.swing.JTextField Correction6_txt;
    private javax.swing.JTextField Correction7_txt;
    private javax.swing.JTextField Correction8_txt;
    private javax.swing.JTextField Correction9_txt;
    private javax.swing.JLabel Hypochlorite_lbl;
    private javax.swing.JTextField Hypochlorite_txt;
    private javax.swing.JLabel Incorrect_lbl;
    private javax.swing.JTextField Incorrect_txt;
    private javax.swing.JLabel Li3PO4_lbl;
    private javax.swing.JTextField Li3PO4_txt;
    private javax.swing.JLabel MagnesiumPhosphate_lbl;
    private javax.swing.JTextField MagnesiumPhosphate_txt;
    private javax.swing.JLabel MnS2_lbl;
    private javax.swing.JTextField MnS2_txt;
    private javax.swing.JLabel NO_lbl;
    private javax.swing.JTextField NO_txt;
    private javax.swing.JLabel NiI3_lbl;
    private javax.swing.JTextField NiI3_txt;
    private javax.swing.JLabel PerbromicAcid_lbl;
    private javax.swing.JTextField PerbromicAcid_txt;
    private javax.swing.JLabel Percarbonate_lbl;
    private javax.swing.JTextField Percarbonate_txt;
    private javax.swing.JLabel Percentage_lbl;
    private javax.swing.JTextField Percentage_txt;
    private javax.swing.JPanel Quiz;
    private javax.swing.JLabel SodiumSulfate_lbl;
    private javax.swing.JTextField SodiumSulfate_txt;
    private javax.swing.JButton SubmitButton;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lbl_CH3COOH;
    // End of variables declaration//GEN-END:variables
}
